# CMake generated Testfile for 
# Source directory: /home/yuqingz/autonomous_driving/baseline/cmake-3.20.0/Tests/CMakeLib
# Build directory: /home/yuqingz/autonomous_driving/baseline/cmake-3.20.0/Tests/CMakeLib
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(CMakeLib.testArgumentParser "/home/yuqingz/autonomous_driving/baseline/cmake-3.20.0/Tests/CMakeLib/CMakeLibTests" "testArgumentParser")
set_tests_properties(CMakeLib.testArgumentParser PROPERTIES  _BACKTRACE_TRIPLES "/home/yuqingz/autonomous_driving/baseline/cmake-3.20.0/Tests/CMakeLib/CMakeLists.txt;68;add_test;/home/yuqingz/autonomous_driving/baseline/cmake-3.20.0/Tests/CMakeLib/CMakeLists.txt;0;")
add_test(CMakeLib.testCTestBinPacker "/home/yuqingz/autonomous_driving/baseline/cmake-3.20.0/Tests/CMakeLib/CMakeLibTests" "testCTestBinPacker")
set_tests_properties(CMakeLib.testCTestBinPacker PROPERTIES  _BACKTRACE_TRIPLES "/home/yuqingz/autonomous_driving/baseline/cmake-3.20.0/Tests/CMakeLib/CMakeLists.txt;68;add_test;/home/yuqingz/autonomous_driving/baseline/cmake-3.20.0/Tests/CMakeLib/CMakeLists.txt;0;")
add_test(CMakeLib.testCTestResourceAllocator "/home/yuqingz/autonomous_driving/baseline/cmake-3.20.0/Tests/CMakeLib/CMakeLibTests" "testCTestResourceAllocator")
set_tests_properties(CMakeLib.testCTestResourceAllocator PROPERTIES  _BACKTRACE_TRIPLES "/home/yuqingz/autonomous_driving/baseline/cmake-3.20.0/Tests/CMakeLib/CMakeLists.txt;68;add_test;/home/yuqingz/autonomous_driving/baseline/cmake-3.20.0/Tests/CMakeLib/CMakeLists.txt;0;")
add_test(CMakeLib.testCTestResourceSpec "/home/yuqingz/autonomous_driving/baseline/cmake-3.20.0/Tests/CMakeLib/CMakeLibTests" "testCTestResourceSpec" "/home/yuqingz/autonomous_driving/baseline/cmake-3.20.0/Tests/CMakeLib")
set_tests_properties(CMakeLib.testCTestResourceSpec PROPERTIES  _BACKTRACE_TRIPLES "/home/yuqingz/autonomous_driving/baseline/cmake-3.20.0/Tests/CMakeLib/CMakeLists.txt;68;add_test;/home/yuqingz/autonomous_driving/baseline/cmake-3.20.0/Tests/CMakeLib/CMakeLists.txt;0;")
add_test(CMakeLib.testCTestResourceGroups "/home/yuqingz/autonomous_driving/baseline/cmake-3.20.0/Tests/CMakeLib/CMakeLibTests" "testCTestResourceGroups")
set_tests_properties(CMakeLib.testCTestResourceGroups PROPERTIES  _BACKTRACE_TRIPLES "/home/yuqingz/autonomous_driving/baseline/cmake-3.20.0/Tests/CMakeLib/CMakeLists.txt;68;add_test;/home/yuqingz/autonomous_driving/baseline/cmake-3.20.0/Tests/CMakeLib/CMakeLists.txt;0;")
add_test(CMakeLib.testGccDepfileReader "/home/yuqingz/autonomous_driving/baseline/cmake-3.20.0/Tests/CMakeLib/CMakeLibTests" "testGccDepfileReader" "/home/yuqingz/autonomous_driving/baseline/cmake-3.20.0/Tests/CMakeLib")
set_tests_properties(CMakeLib.testGccDepfileReader PROPERTIES  _BACKTRACE_TRIPLES "/home/yuqingz/autonomous_driving/baseline/cmake-3.20.0/Tests/CMakeLib/CMakeLists.txt;68;add_test;/home/yuqingz/autonomous_driving/baseline/cmake-3.20.0/Tests/CMakeLib/CMakeLists.txt;0;")
add_test(CMakeLib.testGeneratedFileStream "/home/yuqingz/autonomous_driving/baseline/cmake-3.20.0/Tests/CMakeLib/CMakeLibTests" "testGeneratedFileStream")
set_tests_properties(CMakeLib.testGeneratedFileStream PROPERTIES  _BACKTRACE_TRIPLES "/home/yuqingz/autonomous_driving/baseline/cmake-3.20.0/Tests/CMakeLib/CMakeLists.txt;68;add_test;/home/yuqingz/autonomous_driving/baseline/cmake-3.20.0/Tests/CMakeLib/CMakeLists.txt;0;")
add_test(CMakeLib.testJSONHelpers "/home/yuqingz/autonomous_driving/baseline/cmake-3.20.0/Tests/CMakeLib/CMakeLibTests" "testJSONHelpers")
set_tests_properties(CMakeLib.testJSONHelpers PROPERTIES  _BACKTRACE_TRIPLES "/home/yuqingz/autonomous_driving/baseline/cmake-3.20.0/Tests/CMakeLib/CMakeLists.txt;68;add_test;/home/yuqingz/autonomous_driving/baseline/cmake-3.20.0/Tests/CMakeLib/CMakeLists.txt;0;")
add_test(CMakeLib.testRST "/home/yuqingz/autonomous_driving/baseline/cmake-3.20.0/Tests/CMakeLib/CMakeLibTests" "testRST" "/home/yuqingz/autonomous_driving/baseline/cmake-3.20.0/Tests/CMakeLib")
set_tests_properties(CMakeLib.testRST PROPERTIES  _BACKTRACE_TRIPLES "/home/yuqingz/autonomous_driving/baseline/cmake-3.20.0/Tests/CMakeLib/CMakeLists.txt;68;add_test;/home/yuqingz/autonomous_driving/baseline/cmake-3.20.0/Tests/CMakeLib/CMakeLists.txt;0;")
add_test(CMakeLib.testRange "/home/yuqingz/autonomous_driving/baseline/cmake-3.20.0/Tests/CMakeLib/CMakeLibTests" "testRange")
set_tests_properties(CMakeLib.testRange PROPERTIES  _BACKTRACE_TRIPLES "/home/yuqingz/autonomous_driving/baseline/cmake-3.20.0/Tests/CMakeLib/CMakeLists.txt;68;add_test;/home/yuqingz/autonomous_driving/baseline/cmake-3.20.0/Tests/CMakeLib/CMakeLists.txt;0;")
add_test(CMakeLib.testOptional "/home/yuqingz/autonomous_driving/baseline/cmake-3.20.0/Tests/CMakeLib/CMakeLibTests" "testOptional")
set_tests_properties(CMakeLib.testOptional PROPERTIES  _BACKTRACE_TRIPLES "/home/yuqingz/autonomous_driving/baseline/cmake-3.20.0/Tests/CMakeLib/CMakeLists.txt;68;add_test;/home/yuqingz/autonomous_driving/baseline/cmake-3.20.0/Tests/CMakeLib/CMakeLists.txt;0;")
add_test(CMakeLib.testString "/home/yuqingz/autonomous_driving/baseline/cmake-3.20.0/Tests/CMakeLib/CMakeLibTests" "testString")
set_tests_properties(CMakeLib.testString PROPERTIES  _BACKTRACE_TRIPLES "/home/yuqingz/autonomous_driving/baseline/cmake-3.20.0/Tests/CMakeLib/CMakeLists.txt;68;add_test;/home/yuqingz/autonomous_driving/baseline/cmake-3.20.0/Tests/CMakeLib/CMakeLists.txt;0;")
add_test(CMakeLib.testStringAlgorithms "/home/yuqingz/autonomous_driving/baseline/cmake-3.20.0/Tests/CMakeLib/CMakeLibTests" "testStringAlgorithms")
set_tests_properties(CMakeLib.testStringAlgorithms PROPERTIES  _BACKTRACE_TRIPLES "/home/yuqingz/autonomous_driving/baseline/cmake-3.20.0/Tests/CMakeLib/CMakeLists.txt;68;add_test;/home/yuqingz/autonomous_driving/baseline/cmake-3.20.0/Tests/CMakeLib/CMakeLists.txt;0;")
add_test(CMakeLib.testSystemTools "/home/yuqingz/autonomous_driving/baseline/cmake-3.20.0/Tests/CMakeLib/CMakeLibTests" "testSystemTools")
set_tests_properties(CMakeLib.testSystemTools PROPERTIES  _BACKTRACE_TRIPLES "/home/yuqingz/autonomous_driving/baseline/cmake-3.20.0/Tests/CMakeLib/CMakeLists.txt;68;add_test;/home/yuqingz/autonomous_driving/baseline/cmake-3.20.0/Tests/CMakeLib/CMakeLists.txt;0;")
add_test(CMakeLib.testUTF8 "/home/yuqingz/autonomous_driving/baseline/cmake-3.20.0/Tests/CMakeLib/CMakeLibTests" "testUTF8")
set_tests_properties(CMakeLib.testUTF8 PROPERTIES  _BACKTRACE_TRIPLES "/home/yuqingz/autonomous_driving/baseline/cmake-3.20.0/Tests/CMakeLib/CMakeLists.txt;68;add_test;/home/yuqingz/autonomous_driving/baseline/cmake-3.20.0/Tests/CMakeLib/CMakeLists.txt;0;")
add_test(CMakeLib.testXMLParser "/home/yuqingz/autonomous_driving/baseline/cmake-3.20.0/Tests/CMakeLib/CMakeLibTests" "testXMLParser")
set_tests_properties(CMakeLib.testXMLParser PROPERTIES  _BACKTRACE_TRIPLES "/home/yuqingz/autonomous_driving/baseline/cmake-3.20.0/Tests/CMakeLib/CMakeLists.txt;68;add_test;/home/yuqingz/autonomous_driving/baseline/cmake-3.20.0/Tests/CMakeLib/CMakeLists.txt;0;")
add_test(CMakeLib.testXMLSafe "/home/yuqingz/autonomous_driving/baseline/cmake-3.20.0/Tests/CMakeLib/CMakeLibTests" "testXMLSafe")
set_tests_properties(CMakeLib.testXMLSafe PROPERTIES  _BACKTRACE_TRIPLES "/home/yuqingz/autonomous_driving/baseline/cmake-3.20.0/Tests/CMakeLib/CMakeLists.txt;68;add_test;/home/yuqingz/autonomous_driving/baseline/cmake-3.20.0/Tests/CMakeLib/CMakeLists.txt;0;")
add_test(CMakeLib.testFindPackageCommand "/home/yuqingz/autonomous_driving/baseline/cmake-3.20.0/Tests/CMakeLib/CMakeLibTests" "testFindPackageCommand")
set_tests_properties(CMakeLib.testFindPackageCommand PROPERTIES  _BACKTRACE_TRIPLES "/home/yuqingz/autonomous_driving/baseline/cmake-3.20.0/Tests/CMakeLib/CMakeLists.txt;68;add_test;/home/yuqingz/autonomous_driving/baseline/cmake-3.20.0/Tests/CMakeLib/CMakeLists.txt;0;")
add_test(CMakeLib.testUVProcessChain "/home/yuqingz/autonomous_driving/baseline/cmake-3.20.0/Tests/CMakeLib/CMakeLibTests" "testUVProcessChain" "/home/yuqingz/autonomous_driving/baseline/cmake-3.20.0/Tests/CMakeLib/testUVProcessChainHelper")
set_tests_properties(CMakeLib.testUVProcessChain PROPERTIES  _BACKTRACE_TRIPLES "/home/yuqingz/autonomous_driving/baseline/cmake-3.20.0/Tests/CMakeLib/CMakeLists.txt;68;add_test;/home/yuqingz/autonomous_driving/baseline/cmake-3.20.0/Tests/CMakeLib/CMakeLists.txt;0;")
add_test(CMakeLib.testUVRAII "/home/yuqingz/autonomous_driving/baseline/cmake-3.20.0/Tests/CMakeLib/CMakeLibTests" "testUVRAII")
set_tests_properties(CMakeLib.testUVRAII PROPERTIES  _BACKTRACE_TRIPLES "/home/yuqingz/autonomous_driving/baseline/cmake-3.20.0/Tests/CMakeLib/CMakeLists.txt;68;add_test;/home/yuqingz/autonomous_driving/baseline/cmake-3.20.0/Tests/CMakeLib/CMakeLists.txt;0;")
add_test(CMakeLib.testUVStreambuf "/home/yuqingz/autonomous_driving/baseline/cmake-3.20.0/Tests/CMakeLib/CMakeLibTests" "testUVStreambuf" "/home/yuqingz/autonomous_driving/baseline/cmake-3.20.0/bin/cmake")
set_tests_properties(CMakeLib.testUVStreambuf PROPERTIES  _BACKTRACE_TRIPLES "/home/yuqingz/autonomous_driving/baseline/cmake-3.20.0/Tests/CMakeLib/CMakeLists.txt;68;add_test;/home/yuqingz/autonomous_driving/baseline/cmake-3.20.0/Tests/CMakeLib/CMakeLists.txt;0;")
add_test(CMakeLib.testCMExtMemory "/home/yuqingz/autonomous_driving/baseline/cmake-3.20.0/Tests/CMakeLib/CMakeLibTests" "testCMExtMemory")
set_tests_properties(CMakeLib.testCMExtMemory PROPERTIES  _BACKTRACE_TRIPLES "/home/yuqingz/autonomous_driving/baseline/cmake-3.20.0/Tests/CMakeLib/CMakeLists.txt;68;add_test;/home/yuqingz/autonomous_driving/baseline/cmake-3.20.0/Tests/CMakeLib/CMakeLists.txt;0;")
add_test(CMakeLib.testCMExtAlgorithm "/home/yuqingz/autonomous_driving/baseline/cmake-3.20.0/Tests/CMakeLib/CMakeLibTests" "testCMExtAlgorithm")
set_tests_properties(CMakeLib.testCMExtAlgorithm PROPERTIES  _BACKTRACE_TRIPLES "/home/yuqingz/autonomous_driving/baseline/cmake-3.20.0/Tests/CMakeLib/CMakeLists.txt;68;add_test;/home/yuqingz/autonomous_driving/baseline/cmake-3.20.0/Tests/CMakeLib/CMakeLists.txt;0;")
add_test(CMakeLib.testCMFilesystemPath "/home/yuqingz/autonomous_driving/baseline/cmake-3.20.0/Tests/CMakeLib/CMakeLibTests" "testCMFilesystemPath")
set_tests_properties(CMakeLib.testCMFilesystemPath PROPERTIES  _BACKTRACE_TRIPLES "/home/yuqingz/autonomous_driving/baseline/cmake-3.20.0/Tests/CMakeLib/CMakeLists.txt;68;add_test;/home/yuqingz/autonomous_driving/baseline/cmake-3.20.0/Tests/CMakeLib/CMakeLists.txt;0;")
subdirs("PseudoMemcheck")
